/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnvelopeIdRouteImport } from './routes/envelope.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopeIdRoute = EnvelopeIdRouteImport.update({
  id: '/envelope/$id',
  path: '/envelope/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/envelope/$id': typeof EnvelopeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/envelope/$id': typeof EnvelopeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/envelope/$id': typeof EnvelopeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/envelope/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/envelope/$id'
  id: '__root__' | '/' | '/envelope/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnvelopeIdRoute: typeof EnvelopeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelope/$id': {
      id: '/envelope/$id'
      path: '/envelope/$id'
      fullPath: '/envelope/$id'
      preLoaderRoute: typeof EnvelopeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvelopeIdRoute: EnvelopeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
